# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v2.2.2
_src_path: gh:FallingColors/hexdummy
advanced: true
capitalize_platforms: false
classname: Bloodcasting
default_branch: main
description: Enhancing the blood casting mechanic from Hexcasting.
display_name: Bloodcasting
github_repo: bloodcasting
github_user: BlueEyedFoxUnderscore
homepage_url: https://blueeyedfoxunderscore.github.io/bloodcasting
java_package: io.github.blueeyedfoxunderscore.bloodcasting
kotlin_package: io.github.blueeyedfoxunderscore.bloodcasting
mappings_name: Mojmap
minecraft_version_in_mod_version: true
mit_license: true
mod_version: 0.1.0
modid: bloodcasting
sources_url: https://github.com/BlueEyedFoxUnderscore/bloodcasting
